baseURL = 'https://birgens.github.io/tromsoastronomi/'
languageCode = 'no'
title = 'Tromsø Astronomiforening'
theme = 'PaperMod'

Paginate = 6

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag = 'tags'

[params]
  site_logo = 'images/logo_kvadratisk.jpg'
  favicon = 'favicon.ico'
  mainSections = ['post']
  recent_posts_number = 3

[[menu.main]]
  name="Hjem"
  url="/"
  weight=1

[[menu.main]]
  name = "Om foreningen"
  url = "/informasjon/"
  weight = 2

